Issue 1060 SMB support for web dav
epam/cloud-pipeline pull request #1078
Opened 2020-04-28 15:52 UTC by SilinPavel

This PR adds new functionality for mounting SMB share storages to webDAV Service.

Because of specific mount prerequisites (like azure storage creds) for mounting, not only WebDAV scripts are changed, but additional changes on deployment process are needed.

To be able to pass storage creds to WebDAV additional kube secret 'cp-region-creds-secret' was added. This secret is used to store all azure region credentials for datastorage accounts.

Each time region is created, api adds storage creds for this region to this kube secret.
WebDAV service mounts this secret as folder and can access creds file for mounting purpose.

2020-05-08 09:23 UTC, mzueva requested changes
Please review usage of `final` keyword in all new methods/classes

2020-05-08 09:23 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/region/CloudRegionManager.java
> +                                Collectors.toMap(azureRegion -> azureRegion.getId().toString(),
This code duplicates logic in aspect, I'd suggest to move it to a separate service and use it in aspect and in `onApplicationEvent ` method

2020-05-08 09:23 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/region/CloudRegionManager.java
> +                                                return Base64.encodeBase64String(mapper.writeValueAsString(creds).getBytes());
Maybe extract this code to some util method or class, since such conversion is used several times

2020-05-08 09:24 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/cluster/KubernetesManager.java
> +    public boolean isSecretExist(final String name) {
I think it is better to call methods `doesSecretExist`

2020-05-08 12:59 UTC, SilinPavel commented
@mzueva done

2020-05-13 08:46 UTC, mzueva approved these changes

2020-05-13 08:46 UTC, merged