Issue 1117 systemd for centos based images
epam/cloud-pipeline pull request #1121
Opened 2020-05-20 14:33 UTC by SilinPavel

Is related to #1117 
Configure systemd to work on centos OS systems if CP_CAP_SYSTEMD_CONTAINER parameter is specified

2020-05-20 16:56 UTC, mzueva requested changes

2020-05-20 16:56 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/execution/PipelineExecutor.java
> +        boolean isSystemdEnabled = ListUtils.emptyIfNull(envVars)
Maybe we should extract method `isParameterEnabled` and use it here and for lines 163-166?

2020-05-20 16:56 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/execution/PipelineExecutor.java
> +    private List<Volume> getVolumes(final boolean isDockerInDockerEnabled, boolean isSystemdEnabled) {
missing `final`

2020-05-20 16:56 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/execution/PipelineExecutor.java
> +    private List<VolumeMount> getMounts(final boolean isDockerInDockerEnabled, boolean isSystemdEnabled) {
missing `final`

2020-05-20 17:35 UTC, SilinPavel commented
@mzueva done

2020-05-21 11:31 UTC, mzueva approved these changes

2020-05-21 11:32 UTC, merged