Issue #1258 Users and regions listing for billing manager
epam/cloud-pipeline pull request #1318
Opened 2020-08-24 18:10 UTC by Wedds

This PR is related to issue #1258

Previously `ROLE_BILLING_MANAGER` was introduced - such users should have full access to billing data. To perform all the operations on billing reports correctly, they must be able to load all the users and regions. Instead of authorizing this role to existing  `CloudRegionController.loadAll` and `UserController.loadUsers` methods, separated endpoints were created. It allows hiding sensitive fields, but `BILLING_MANAGER` will be able to proceed billing reports.

2020-08-25 14:31 UTC, mzueva requested changes
I'd suggest not to hard-link these new methods to billing and make them usable for general `ROLE_USER`.

2020-08-25 14:35 UTC, mzueva requested changes

2020-08-25 14:35 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/controller/region/CloudRegionController.java
> +    @GetMapping("/billing")
Let's rename endpoint `/billing` -> `/info`

2020-08-25 14:35 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/controller/user/UserController.java
> +    @RequestMapping(value = "/users/billing", method = RequestMethod.GET)
Let's rename `/users/billing` -> `/users/info`

2020-08-25 14:35 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/controller/user/UserController.java
> +    @RequestMapping(value = "/users/billing", method = RequestMethod.GET)
`@RequestMapping` -> `@GetMapping`

2020-08-25 14:35 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/entity/billing/RegionForBilling.java
> +public class RegionForBilling {
Let's rename `RegionForBilling` -> `CloudRegionInfo`

2020-08-25 14:35 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/region/CloudRegionApiService.java
> +    @PreAuthorize(AclExpressions.FULL_BILLING_ACCESS)
access for `ROLE_USER`

2020-08-25 14:35 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/user/UserApiService.java
> +    @PreAuthorize(FULL_BILLING_ACCESS)
access for `ROLE_USER`

2020-08-25 16:08 UTC, Wedds commented on api/src/main/java/com/epam/pipeline/controller/region/CloudRegionController.java
> +    @GetMapping("/billing")
Done

2020-08-25 16:08 UTC, Wedds commented on api/src/main/java/com/epam/pipeline/controller/user/UserController.java
> +    @RequestMapping(value = "/users/billing", method = RequestMethod.GET)
Done

2020-08-25 16:08 UTC, Wedds commented on api/src/main/java/com/epam/pipeline/controller/user/UserController.java
> +    @RequestMapping(value = "/users/billing", method = RequestMethod.GET)
Done

2020-08-25 16:08 UTC, Wedds commented on api/src/main/java/com/epam/pipeline/entity/billing/RegionForBilling.java
> +public class RegionForBilling {
Done

2020-08-25 16:08 UTC, Wedds commented on api/src/main/java/com/epam/pipeline/manager/region/CloudRegionApiService.java
> +    @PreAuthorize(AclExpressions.FULL_BILLING_ACCESS)
Done

2020-08-25 16:08 UTC, Wedds commented on api/src/main/java/com/epam/pipeline/manager/user/UserApiService.java
> +    @PreAuthorize(FULL_BILLING_ACCESS)
Done

2020-08-26 09:05 UTC, mzueva requested changes

2020-08-26 09:05 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/region/CloudRegionApiService.java
> +    public List<CloudRegionInfo> loadAllRegionsInfo() {
We still need `@PreAuthorize` annotation here `hasRole('ADMIN') OR hasRole('ROLE_USER')`

2020-08-26 09:05 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/user/UserApiService.java
> +    public List<UserInfo> loadUsersInfo() {
We still need @PreAuthorize annotation here hasRole('ADMIN') OR hasRole('ROLE_USER')

2020-08-26 10:13 UTC, mzueva approved these changes

2020-08-26 10:13 UTC, merged