Issue #1404: Unfinished tests for LogApiService.class
epam/cloud-pipeline pull request #1418
Opened 2020-09-18 14:21 UTC by YouKofan

Unfinished (and not working) tests for LogApiService. Constantly getting an error "Expected exception: org.springframework.security.access.AccessDeniedException", despite the fact that the test parameters specify this expected exception.

2020-09-23 14:21 UTC, ekazachkova requested changes

2020-09-23 14:21 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/log/LogApiServiceTest.java
> +@RunWith(SpringRunner.class)
Could we move tests configuration setting to the separate class (to use that in the future tests) ?

2020-09-23 14:21 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/log/LogApiServiceTest.java
> +    @Autowired
Why we should use `@Autowire` here?

2020-09-23 14:21 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/log/LogApiServiceTest.java
> +@SpringBootTest(classes = {AclTestBeans.class, AclSecurityConfiguration.class})
I would prefer to use `@ContextConfiguration` here.

2020-09-23 14:21 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/log/LogApiServiceTest.java
> +    private AuthManager mockAuthManager;
Do we really need this mock?

2020-09-23 14:21 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/log/LogApiServiceTest.java
> +    private static final String UNAUTHORIZED = "Unauthorized";
Could we rename this filed to `USER_ROLE` (or something similar with non-admin meaning)?

2020-09-23 14:21 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/log/LogApiServiceTest.java
> +    private static final String UNAUTHORIZED = "Unauthorized";
Could we move this filed and `ADMIN_ROLE` field to `AbstractAclTest` since we will need this values into the future tests?

2020-09-23 14:21 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/log/LogApiServiceTest.java
> +}
Could  you please add an empty line at the end of the file? (here and in other places)

2020-09-23 14:21 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/log/LogApiServiceTest.java
> +    private LogManager logManager;
I really like the idea to name such fields with prefix `mock` (as it was done for `AuthManger`). Could you please follow this strategy here?

2020-09-23 14:21 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/log/LogApiServiceTest.java
> +    public void shouldAllowAccessToLogPagination() {
Could you please rename such tests like `...ForAdmin` (or something similar)?

2020-09-23 14:21 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/log/LogApiServiceTest.java
> +    public void shouldDenyAccessToLogPagination() {
Could you please rename such tests like `...ForNotAdmin` (or something similar)?

2020-09-23 14:21 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/log/LogApiServiceTest.java
> + * Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
Please, pay attention on the years in licences. The last year should be equal to current.

2020-09-24 10:07 UTC, YouKofan commented on api/src/test/java/com/epam/pipeline/acl/log/LogApiServiceTest.java
> +    @Autowired
I use this annotation to send to LogApiServiceTest the necessary beans for a successful test. Do we have any alternatives?

2020-09-25 15:14 UTC, closed without merging