Issue #1404: Implemented tests for BillingApiService
epam/cloud-pipeline pull request #1461
Opened 2020-10-05 11:40 UTC by YouKofan

Implement tests for billing package - #1404
Implemented tests for BillingApiService.
Signed-off-by: Iurii_Kofanov youkofan@gmail.com

2020-10-06 11:32 UTC, ekazachkova approved these changes

2020-10-06 13:25 UTC, ekazachkova requested changes
add license please

2020-10-06 17:18 UTC, ekazachkova approved these changes

2020-10-07 10:14 UTC, mzueva approved these changes

2020-10-07 10:15 UTC, merged