Issue #1404: Implemented tests for ContextualPreferenceApiService
epam/cloud-pipeline pull request #1495
Opened 2020-10-14 10:20 UTC by YouKofan

Implemented tests for ContextualPreferenceApiService
Issue - #1404
Signed-off-by: Iurii_Kofanov <youkofan@gmail.com>

2020-10-15 08:11 UTC, tcibinan commented on api/src/test/java/com/epam/pipeline/acl/contextual/ContextualPreferenceApiServiceTest.java
> +        preferenceApiService.loadAll();
There is a helpful method in `CustomAssertions` utility class. Probably it is better to use such method to assert exceptions rather than using `@Test(expected = AccessDeniedException.class)` cause it allows us to specify only a single line that should fail.

```java
assertThrows(AccessDeniedException.class, () -> preferenceApiService.loadAll())
```

2020-10-15 08:11 UTC, tcibinan commented on api/src/test/java/com/epam/pipeline/acl/contextual/ContextualPreferenceApiServiceTest.java
> +    private final ContextualPreferenceExternalResource cpeResource =
It seems fine to just call it `externalResource` or even `resource` because we are already in the context of the contextual preference test class.

2020-10-15 08:11 UTC, tcibinan commented on api/src/test/java/com/epam/pipeline/acl/contextual/ContextualPreferenceApiServiceTest.java
> +        List<ContextualPreference> resultPreferenceList = preferenceApiService.loadAll();
What about calling this loaded preferences list just `loadedPreferences`. Such `result` prefix is just a boilerplate giving no additional meaning to the reader :)

2020-10-15 08:11 UTC, tcibinan commented on api/src/test/java/com/epam/pipeline/acl/contextual/ContextualPreferenceApiServiceTest.java
> +    public void shouldSearchContextualPreference() {
We expect here to be at least a simple user role here so let's add corresponding `@WithMockUser` annotation.

2020-10-15 08:11 UTC, tcibinan commented on api/src/test/java/com/epam/pipeline/acl/contextual/ContextualPreferenceApiServiceTest.java
> +        List<ContextualPreference> resultPreferenceList = preferenceApiService.loadAll();
In case where there is only one assert in the test method we can even inline the variable and don't think about naming it at all.

2020-10-19 10:43 UTC, tcibinan commented on api/src/test/java/com/epam/pipeline/acl/contextual/ContextualPreferenceApiServiceTest.java
> +    @WithMockUser(roles = SIMPLE_USER_ROLE)
As discussed with the team let's use `@WithMockUser(username = SIMPLE_USER)` wherever possible. Even while testing methods without acl annotations at all.

2020-10-19 12:54 UTC, tcibinan approved these changes

2020-10-22 10:16 UTC, mzueva requested changes
Please, fix checkstyle for ContextualPreferenceApiServiceTest class

2020-10-27 13:11 UTC, merged