Issue #1404: Implemented tests for DockerRegistryApiService
epam/cloud-pipeline pull request #1544
Opened 2020-11-05 13:41 UTC by cryteq

This PR is related to issue #1404 and contains tests implementation for `DockerRegistryApiService`

2020-11-10 14:37 UTC, YouKofan commented on api/src/test/java/com/epam/pipeline/acl/docker/DockerRegistryApiServiceTest.java
> +        assertThat(mockDockerRegistryManager.delete(ID, true)).isEqualTo(dockerRegistry);
Apparently, we should use the `dockerRegistryApiService` here, not the `mockDockerRegistryManager`. And also in the test below.

2020-11-11 10:42 UTC, ekazachkova requested changes

2020-11-11 10:42 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/test/creator/docker/ToolCreatorUtils.java
> +    public static Tool getTool(String owner) {
1. To my mind it would be better to overload the method
2. Could we add final to method argument?

2020-11-11 10:42 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/test/creator/docker/DockerCreatorUtils.java
> +    public static DockerRegistry getDockerRegistry(String owner) {
1. To my mind it would be better to overload the method
2. Could we add final to method argument?

2020-11-11 10:42 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/test/creator/docker/DockerCreatorUtils.java
> +    public static DockerRegistryList getDockerRegistryList(String owner) {
1. Do not forget to add `final`
2. Do we really need this method?

2020-11-11 10:42 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/DockerRegistryApiServiceTest.java
> +public class DockerRegistryApiServiceTest extends AbstractAclTest {
Could you add a simple tests for methods with `AclTree` annotation?

2020-11-18 11:38 UTC, ekazachkova requested changes

2020-11-18 11:38 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/test/creator/docker/DockerCreatorUtils.java
> +        final Tool tool = new Tool();
Could it be realized like:
```
return getTool(null, null)
```
?

2020-11-18 11:38 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/DockerRegistryApiServiceTest.java
> +
Could you please remove empty line?

2020-11-18 11:38 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/DockerRegistryApiServiceTest.java
> +        initAclEntity(emptyToolGroupWithoutPermission, AclPermission.READ);
It looks a bit confusing: you are granting permission to object with name `*WithoutPermission`

2020-11-18 11:38 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/DockerRegistryApiServiceTest.java
> +        dockerRegistryWithTools.setGroups(toolGroups);
Class fields mutation makes code confusing. To my mind it would more clearly to refactor this lines:
```
toolGroup.setTools(toolList);
toolGroupWithoutPermission.setTools(toolList);
dockerRegistryWithTools.setGroups(toolGroups);
```
I would suggest two options:
1. create a new objects into the test
2. initialize this fields at the tests class beginning

2020-11-18 11:38 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/DockerRegistryApiServiceTest.java
> +        assertThat(dockerRegistryChildren.size()).isEqualTo(toolGroups.size());
Maybe `assertThat(dockerRegistryChildren).containsAll(toolGroups);` would be enough?

2020-11-18 11:38 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/DockerRegistryApiServiceTest.java
> +        assertThat(dockerRegistryChildren.size()).isEqualTo(toolGroups.size());
If so, could you please check it for other places? (and think about common method)

2020-11-18 11:38 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/DockerRegistryApiServiceTest.java
> +        assertThat(toolGroupWithoutPermissionLeaves.size()).isEqualTo(1);
Could we use `hasSize` here?

2020-11-18 11:38 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/DockerRegistryApiServiceTest.java
> +        assertThat(toolGroupWithoutPermissionLeaves.size()).isEqualTo(1);
If so, could you please fix it for other methods?

2020-11-18 11:38 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/DockerRegistryApiServiceTest.java
> +        final DockerRegistry returnedDr = (DockerRegistry) dockerRegistryApiService
Could we store `dockerRegistryApiService.loadAllRegistriesContent().getChildren()` into the local field?

2020-11-18 11:38 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/DockerRegistryApiServiceTest.java
> +        assertPartialDockerRegistryAclTree(returnedDr);
Is it possible to rename this method to more clear?

2020-11-18 11:38 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/DockerRegistryApiServiceTest.java
> +        final List<? extends AbstractSecuredEntity> toolGroupLeaves = registry.getChildren().get(0).getLeaves();
Could we refactor this logic somehow: list.get(index) is not clear? (Maybe pick methods for each requested entity? by Id?)

2020-12-01 10:01 UTC, ekazachkova approved these changes

2020-12-07 10:42 UTC, merged