Issue 1404: Implemented tests for ToolApiService
epam/cloud-pipeline pull request #1545
Opened 2020-11-05 14:13 UTC by cryteq

This PR is related to issue #1404 and contains tests implementation for `ToolApiService`

2020-11-12 16:11 UTC, ekazachkova requested changes

2020-11-12 16:11 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/ToolApiServiceTest.java
> +    private static final int READ_PERMISSION = 1;
Let's move this constants to `CommonCreatorConstants` class.

2020-11-12 16:11 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/ToolApiServiceTest.java
> +        assertThat(toolApiService.loadTool("", TEST_STRING)).isEqualTo(tool);
Could we use `StringUtils.EMPTY` or other meaningful name?

2020-11-12 16:11 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/ToolApiServiceTest.java
> +        doReturn(SecurityContextHolder.getContext().getAuthentication()).when(mockAuthManager).getAuthentication();
Maybe it would be useful (for other tests too) to create a new common method e.g. `mockSecurityContext`?

2020-11-12 16:11 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/acl/docker/ToolApiServiceTest.java
> +
I would rather not divide this logic: `doReturn(SecurityContextHolder.getContext().getAuthentication()).when(mockAuthManager).getAuthentication();` is another mock in this test.

2020-11-16 10:11 UTC, ekazachkova approved these changes

2020-11-18 07:54 UTC, YouKofan approved these changes

2020-11-18 11:16 UTC, merged