Issue #1687: rewritten tests (replacing Spring test context with simp…
epam/cloud-pipeline pull request #1693
Opened 2020-12-28 10:46 UTC by YouKofan

Issue #1687

Signed-off-by: Iurii_Kofanov <youkofan@gmail.com>

2020-12-28 14:28 UTC, ekazachkova requested changes

2020-12-28 14:28 UTC, ekazachkova commented on api/src/main/java/com/epam/pipeline/security/UserAccessService.java
> +@NoArgsConstructor(force = true)
I would prefer to add changes to tests class instead of service. For example:
```
UserAccessService accessService = new UserAccessService(userManager, true)
```

2020-12-28 14:28 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/security/saml/SAMLUserDetailsServiceImplTest.java
>          String[] mockAttributesArray = {SAML_ATTRIBUTE_1, SAML_ATTRIBUTE_2};
Let's make this field final

2020-12-28 14:28 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/security/saml/SAMLUserDetailsServiceImplTest.java
>      private void mockUserDoesNotExistSituation() {
Let's reorganize methods order: the test methods shall above others

2020-12-28 14:28 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/security/saml/SAMLUserDetailsServiceImplTest.java
>          user.setGroups(Stream.of(SAML_ATTRIBUTE_1).collect(Collectors.toList()));
Let's add a test fixes too: do we need this assignment?

2020-12-28 14:28 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/security/saml/SAMLUserDetailsServiceImplTest.java
>          Assert.assertEquals(expectedUserContext.getUsername(), actualUserContext.getUsername());
Let's move this lines into the separate method:
```
Assert.assertEquals(expectedUserContext.getUsername(), actualUserContext.getUsername());
Assert.assertEquals(expectedUserContext.getGroups(), actualUserContext.getGroups());
```

2020-12-30 09:32 UTC, ekazachkova requested changes

2020-12-30 09:32 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/security/saml/SAMLUserDetailsServiceImplTest.java
> +        spyAccessService = Mockito.spy(new UserAccessService(mockUserManager, true));
Let's stick to a single mock strategy and use annotation:
```
@Spy
private final UserAccessService spyAccessService = new UserAccessService(mockUserManager, true);
```

2020-12-30 09:32 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/security/saml/SAMLUserDetailsServiceImplTest.java
>          user.setGroups(Stream.of(SAML_ATTRIBUTE_1).collect(Collectors.toList()));
Could you please check this comment?

2020-12-30 11:03 UTC, YouKofan commented on api/src/test/java/com/epam/pipeline/security/saml/SAMLUserDetailsServiceImplTest.java
>          user.setGroups(Stream.of(SAML_ATTRIBUTE_1).collect(Collectors.toList()));
You're right - call of this method is redundant here, so it was deleted.

2020-12-30 11:15 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/security/saml/SAMLUserDetailsServiceImplTest.java
>          user.setGroups(Stream.of(SAML_ATTRIBUTE_1).collect(Collectors.toList()));
No, it was'n.

2020-12-30 14:40 UTC, ekazachkova requested changes

2020-12-30 14:40 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/security/saml/SAMLUserDetailsServiceImplTest.java
> +        when(mockMessageHelper.getMessage(anyString(), any())).thenReturn(TEST_STRING);
It seems that this mock doesn't affect anything.

2020-12-30 15:05 UTC, ekazachkova requested changes

2020-12-30 15:05 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/security/saml/SAMLUserDetailsServiceImplTest.java
> +    private MessageHelper mockMessageHelper;
Let's add `@SuppressWarnings("PMD.UnusedPrivateField")` to avoid `pmdTest` task failure.

2021-01-11 10:57 UTC, ekazachkova approved these changes

2021-01-13 16:18 UTC, merged