Issue #1802 Add pause/resume operations to the pipe CLI
epam/cloud-pipeline pull request #1814
Opened 2021-02-17 10:31 UTC by Wedds

This PR is related to issue # 1802

It brings `pause` and` resume` operations to the pipe CLI.

Besides, it is allowing specifying commands, which abortion will be indicated with a custom message.

2021-02-20 09:17 UTC, ekazachkova requested changes

2021-02-20 09:17 UTC, ekazachkova commented on pipe-cli/src/utilities/pipeline_run_operations.py
> +                    click.echo('Failed pausing RunID {} of "{}@{}"'.format(run_id, pipeline_name, pipeline_version))
Let's add `err=True` since this is the error message

2021-02-20 09:17 UTC, ekazachkova commented on pipe-cli/pipe.py
> +    """Resumes a running pipeline
Maybe `paused` would be more clear instead of `running`?

2021-02-24 08:06 UTC, Wedds commented on pipe-cli/src/utilities/pipeline_run_operations.py
> +                    click.echo('Failed pausing RunID {} of "{}@{}"'.format(run_id, pipeline_name, pipeline_version))
Done

2021-02-24 08:06 UTC, Wedds commented on pipe-cli/pipe.py
> +    """Resumes a running pipeline
Done

2021-02-24 11:57 UTC, ekazachkova approved these changes

2021-02-24 12:49 UTC, merged