Issue 166 New type of notification High resource consuming
epam/cloud-pipeline pull request #215
Opened 2019-04-25 13:08 UTC by SilinPavel

This PR related to #166. 
Adds new type of notification

2019-04-26 09:59 UTC, mzueva requested changes

2019-04-26 09:59 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/dao/monitoring/MonitoringESDao.java
> +    public Map<String, Double> loadUsageRateMetrics(ELKUsageMetric metric, Collection<String> podIds,
Let's try to stuck to `final` args, variables and fields style.

2019-04-26 09:59 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/dao/monitoring/MonitoringESDao.java
> +        limit.forEach((k, v) -> usage.merge(k, v, this::getRate));
Prefer creation of a new collection instead of mutating an existing one

2019-04-26 09:59 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/dao/notification/MonitoringNotificationDao.java
> +import static com.epam.pipeline.entity.notification.NotificationSettings.*;
Do not use star imports

2019-04-26 09:59 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/dao/notification/MonitoringNotificationDao.java
> +        return items.isEmpty() ? null : items.get(0);
Let's return `Optional` for such methods

2019-04-26 09:59 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/entity/cluster/monitoring/ELKUsageMetric.java
> +    ELKUsageMetric(String name, String timestamp) {
`@AllArgsContructor`

2019-04-26 09:59 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/cluster/performancemonitoring/ResourceMonitoringManager.java
> +import static com.epam.pipeline.manager.preference.SystemPreferences.*;
Please, do not use star imports

2019-04-26 09:59 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/cluster/performancemonitoring/ResourceMonitoringManager.java
> +        running.forEach((pod, run) -> {
Prefer usage of `map` to create a new collection, instead of mutating an existing one

2019-04-26 09:59 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/dao/notification/MonitoringNotificationDao.java
> +    public void deleteNotificationTimestampsForPipeline(Long pipelineId) {
Missing `@Transactional`?

2019-04-26 09:59 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/notification/NotificationManager.java
> +        if (CollectionUtils.isEmpty(settings.getInformedUserIds())) {
`return ListUtils.emptyIfNull(settings.getInformedUserIds())`

2019-04-26 09:59 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/notification/NotificationManager.java
> +            ExtendedRole extendedRole = roleManager.loadRoleWithUsers(DefaultRoles.ROLE_ADMIN.getId());
I'd suggest to merge collections instead of adding elements to one of them

2019-04-26 09:59 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/preference/SystemPreferences.java
> +     * Level of memory load, blow which a Run is considered `overloaded`
`blow` -> `below`

2019-04-29 09:48 UTC, mzueva requested changes

2019-04-29 09:48 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/dao/monitoring/MonitoringESDao.java
> +        limits.forEach((pod,  value) -> {
Better use `map` for this case

2019-04-29 09:48 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/notification/NotificationManager.java
> +                .collect(Collectors.toMap(PipelineUser::getUserName, user -> user));
Looks like a code dupe with line 290

2019-04-29 11:40 UTC, SilinPavel commented
@mzueva  corrections are done

2019-04-29 12:28 UTC, mzueva approved these changes

2019-04-29 12:28 UTC, merged