Support manager node users and groups sharing within a cluster
epam/cloud-pipeline pull request #2201
Opened 2021-10-08 09:16 UTC by tcibinan

Resolves #2195.

The pull request brings support for cluster-wide manager node users and groups sharing.

The following list of run parameters can be used to configure cluster users and groups sharing:
- `CP_CAP_SHARE_USERS` enables cluster users and groups sharing. Defaults to `false`.
- `CP_CAP_SHARE_USERS_LOGGING_LEVEL` configures logging level in a GUI log. Defaults to `ERROR`. 
- `CP_CAP_SHARE_USERS_LOGGING_LEVEL_LOCAL` configures logging level in a local log file. Defaults to `DEBUG`.

Local log file can be found here `$LOG_DIR/configure_shared_users.log` or `/runs/pipeline-12345/logs/configure_shared_users.log`.

2021-10-13 10:30 UTC, mzueva requested changes

2021-10-13 10:30 UTC, mzueva commented on workflows/pipe-common/scripts/configure_shared_users.py
> +            execute('sshfs -o ro,allow_other root@lizardfs-master:{etc_directory} {etc_directory_shared}'
We need to check that lizard fs is used as shared fs or support NFS & Lustre masters as well

2021-10-13 10:30 UTC, mzueva commented on workflows/pipe-common/scripts/configure_shared_users.py
> +    api_token = os.environ['API_TOKEN']
Unused variable?

2021-10-14 10:18 UTC, tcibinan commented on workflows/pipe-common/scripts/configure_shared_users.py
> +            execute('sshfs -o ro,allow_other root@lizardfs-master:{etc_directory} {etc_directory_shared}'
Thanks. From now on parent run pod ip will be used rather than some shared fs specific host name.

2021-10-14 10:18 UTC, tcibinan commented on workflows/pipe-common/scripts/configure_shared_users.py
> +    api_token = os.environ['API_TOKEN']
Yeap.

2021-10-20 14:09 UTC, mzueva approved these changes

2021-10-21 06:32 UTC, merged