High resource comsuming notification
epam/cloud-pipeline pull request #244
Opened 2019-05-06 16:06 UTC by SilinPavel

Update for issue #166

Earlier, #215 was merged, but it uses `pod_container` data from heapster to calculate `memory` and `disk` usage. It turns out that we should use `node` data for this propose.
This PR brings necessary changes.
It also brings convenient way to fetch performance data from heapser as `Map<String, Double>` with `MetricRequester` interface.

2019-05-07 19:12 UTC, sidoruka commented
@SilinPavel, could you please fix the naming with of the notification-related json/html? Missed that for #215.
If I remember right - deployment scripts assume that html/json files, applied to the notification, shall have the same name as the notification type.
Currently, they are different and a new deployment have empty config/content of the new notification type: files are named like `HIGH_RESOURCE_CONSUMING_RUN` while a notification is called `HIGH_CONSUMED_RESOURCES`

2019-05-07 19:13 UTC, sidoruka requested changes
@SilinPavel, could you please fix the naming with of the notification-related json/html? Missed that for #215.
If I remember right - deployment scripts assume that html/json files, applied to the notification, shall have the same name as the notification type.
Currently, they are different and a new deployment have empty config/content of the new notification type: files are named like `HIGH_RESOURCE_CONSUMING_RUN` while a notification is called `HIGH_CONSUMED_RESOURCES`

2019-05-08 08:59 UTC, SilinPavel commented
@sidoruka, indeed, fixed with b40f6dc

2019-05-08 13:43 UTC, mzueva approved these changes

2019-05-08 13:52 UTC, mzueva approved these changes

2019-05-08 13:52 UTC, merged