Gui tests 2642
epam/cloud-pipeline pull request #2726
Opened 2022-07-08 12:14 UTC by maryvictol

This PR adds e2e tests for Restrict a count of the instances to launch #2642

2023-01-18 15:57 UTC, kamyshova requested changes

2023-01-18 15:57 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/RunsMenuAO.java
> +    public PipelineRunFormAO rerun(final String runId, final String pipelineName) {
Parameter 'pipelineName' is not used

2023-01-18 15:57 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/SettingsPageAO.java
> +                    actions().sendKeys(user.login).perform();
I suppose we should pass the `name` value instead of `user.login`

2023-04-03 11:18 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/RunsMenuAO.java
> +    public PipelineRunFormAO rerun(final String runId, final String pipelineName) {
Extra parameter 'pipelineName has been removed

2023-04-03 12:37 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/SettingsPageAO.java
> +                    actions().sendKeys(user.login).perform();
Done

2023-04-05 00:16 UTC, closed without merging