Add support for regional desktop connections
epam/cloud-pipeline pull request #2731
Opened 2022-07-13 10:09 UTC by tcibinan

Relates to #1715.

The pull request brings support for regional nomachine/nicedcv desktop connections to both linux and windows runs. Depending on the chosen region the desktop connections will use regional proxies from now on. Previously default region proxy was used no matter what.

2022-07-14 12:22 UTC, SilinPavel requested changes

2022-07-14 12:22 UTC, SilinPavel commented on workflows/pipe-common/scripts/serve_desktop.py
> +    if Config.personal and is_windows():
I would move it to separate (username resolving) method similar to `_read_template_file` and `_resolve_edge` just to make it more clean

2022-07-15 07:26 UTC, tcibinan commented on workflows/pipe-common/scripts/serve_desktop.py
> +    if Config.personal and is_windows():
Done

2022-07-15 08:02 UTC, SilinPavel approved these changes

2022-07-15 11:30 UTC, merged

2022-07-15 12:33 UTC, tcibinan commented
Cherry-picked to `release/0.16` via 59f14fb4a963c23c50a3aa21f8538270becc1ee4.