Issue 3159 sge worker status
epam/cloud-pipeline pull request #3179
Opened 2023-04-04 15:53 UTC by ekazachkova

The current PR provides implementation for issue #3159 

The following changes were added:
 - a new tag `SGE_IN_USE` is added for all active runs
 - `sge_setup_master` launches `autoscale_sge.py` for all cases (removed `CP_CAP_AUTOSCALE` flag restriction)

2023-04-06 09:09 UTC, tcibinan requested changes

2023-04-06 09:09 UTC, tcibinan commented on workflows/pipe-common/scripts/autoscale_sge.py
> +    Logger.info('Static hosts have been initialized.')
Grid Engine autoscaling script restarts multiple times throughout run's lifetime.

In case run restarts and _run/parents/runid_ method is called then it will return all running and stopped both static and autoscaling child runs. In order to manage only static child runs the runs shall be filtered by the following parameter _cluster_role_type != additional_.

Moreover we should be very careful with calling _common_utils.retrieve_pod_name_ here because it makes an API request every time. For big clusters of hundreds of child runs this may be dangerous.

2023-04-06 09:09 UTC, tcibinan commented on workflows/pipe-common/scripts/autoscale_sge.py
> +    if static_hosts_number:
Grid engine autoscaler manages static hosts only if the current queue is static. If queue is static then static hosts are part of this queue. Therefore, we should you the following if here:

```suggestion
    if queue_static and static_hosts_number:
```

2023-04-06 09:09 UTC, tcibinan commented on workflows/pipe-common/scripts/autoscale_sge.py
> +    run_activation_timeout = 30
Let's call it _tagging_active_timeout_ and use environment variable _CP_CAP_AUTOSCALE_ACTIVE_TIMEOUT_ to get the corresponding value with _30_ as a default value.

2023-04-06 09:09 UTC, tcibinan commented on workflows/pipe-common/scripts/autoscale_sge.py
> +        autoscaling_hosts_number = 0
Let's add a small log message just to be clear that this is a special autoscaler launch.

```suggestion
    if not autoscale_enabled:
        Logger.info('Using non autoscaling mode...')
        autoscaling_hosts_number = 0
```

2023-04-06 09:09 UTC, tcibinan commented on workflows/pipe-common/scripts/autoscale_sge.py
> +        if tags.__contains__(self._WORKER_TAG):
Let's use more pythonish syntax:

```suggestion
        if self._WORKER_TAG in tags:
```

2023-04-06 09:09 UTC, tcibinan commented on workflows/pipe-common/scripts/autoscale_sge.py
> +                self._untag_run(monitored_host)
Though I do appreciate having lots of logs, at the moment I would suggest to reduce the amount of logs to only two records (add/remove tag). In the current logging setup we don't have a proper usage of logging levels (debug in specific). This log is extremely important and we shall keep it brief and human readable even for clusters even with hundreds of workers.

In the future I want to use _pipeline.log.logger.CloudPipelineLogger_ which does better job in logging level management. Once it is used, we can add more debug logs. But for now let's keep it brief.

```
...
Logger.info('Marking active host %s...' % current_host)
...
Logger.info('Marking inactive host %s...' % current_host)
```

2023-04-06 09:45 UTC, tcibinan commented on workflows/pipe-common/scripts/autoscale_sge.py
> +    Logger.info('Static hosts have been initialized.')
Seems to be resolved with the usage of filesystem host storages and comment below.

2023-04-06 12:30 UTC, tcibinan requested changes

2023-04-06 12:30 UTC, tcibinan commented on workflows/pipe-common/scripts/autoscale_sge.py
> +            Logger.warn('Tags processing has failed: %s' % str(e))
Let's log error stacktraces as well.

```suggestion
        except Exception as e:
            Logger.warn('Tags processing has failed: %s' % str(e))
            Logger.warn(traceback.format_exc())
```

2023-04-06 13:31 UTC, tcibinan approved these changes

2023-04-07 10:28 UTC, mzueva approved these changes

2023-04-07 10:28 UTC, merged