Gui improvements 10 04 23
epam/cloud-pipeline pull request #3250
Opened 2023-05-25 22:35 UTC by maryvictol

This PR updates run logs locators after UI update.

2023-06-12 20:55 UTC, kamyshova requested changes

2023-06-12 20:55 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/DataStoragesFeaturesTest.java
> +            loginAs(admin);
Can we use loginAsAdminAndPerform() here?

2023-06-12 20:55 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/DataStoragesFeaturesTest.java
> +        loginAs(admin);
Can we use loginAsAdminAndPerform() here?

2023-06-12 20:55 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/DataStoragesFeaturesTest.java
> +            loginAs(admin);
The same as above

2023-06-12 20:55 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/PipelineEditingTest.java
> +                .waitUntilRenameButtonAppears(RENAMED_FILE_NAME)
Could we update waitUntilRenameButtonAppears() to while loop to avoid sleep()?

2023-06-12 20:55 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/HotNodePoolsAO.java
> +            context().find(byXpath("//*[contains(@class, 'ant-select-selection__placeholder') and contains(., 'Select property')]")).click();
Add a line break, please

2023-06-12 20:55 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/LogAO.java
> +            entry(NESTED_RUNS, $(withText("Nested runs:")).closest("tr").find(byXpath("td/div[2]/a[1]"))),
Could we avoid to locating element by `byXpath`?

2023-06-12 20:55 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/LogAO.java
> +               .ensure(byXpath(".//div[contains(@class,'cp-console-output')]/div[contains(@class,'un-task-logs__console-line')]"),
Fix the line break, please

2023-06-12 20:55 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PermissionTabAO.java
> +                        userName))).click();
Fix the line break, please

2023-06-12 20:55 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +import static com.codeborne.selenide.Condition.enabled;
Move to other static imports, please

2023-06-12 20:55 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +import static com.epam.pipeline.autotests.utils.C.DEFAULT_TIMEOUT;
Move to other static imports, please

2023-06-12 20:55 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/RunsMenuAO.java
> +import static com.epam.pipeline.autotests.utils.C.DEFAULT_REGISTRY;
Move to other static imports, please

2023-06-12 20:55 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/RunsMenuAO.java
> +import static com.epam.pipeline.autotests.utils.Utils.nameWithoutGroup;
Move to other static imports, please

2023-06-14 20:40 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/RunsMenuAO.java
> +import static com.epam.pipeline.autotests.utils.Utils.nameWithoutGroup;
Done

2023-06-14 20:40 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/RunsMenuAO.java
> +import static com.epam.pipeline.autotests.utils.C.DEFAULT_REGISTRY;
Done

2023-06-14 20:49 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +import static com.epam.pipeline.autotests.utils.C.DEFAULT_TIMEOUT;
Done

2023-06-14 20:49 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +import static com.codeborne.selenide.Condition.enabled;
Done

2023-06-14 21:14 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/LogAO.java
> +               .ensure(byXpath(".//div[contains(@class,'cp-console-output')]/div[contains(@class,'un-task-logs__console-line')]"),
Done

2023-06-14 21:15 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PermissionTabAO.java
> +                        userName))).click();
Done

2023-06-14 22:12 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/DataStoragesFeaturesTest.java
> +            loginAs(admin);
Done

2023-06-14 22:12 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/DataStoragesFeaturesTest.java
> +        loginAs(admin);
Done

2023-06-20 09:24 UTC, kamyshova approved these changes

2023-06-20 09:27 UTC, merged