Gui improvements 08 11 23
epam/cloud-pipeline pull request #3432
Opened 2024-01-26 14:00 UTC by maryvictol

2024-04-17 09:12 UTC, kamyshova requested changes

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/LaunchLimitMountsTest.java
> +                .ensureParameterIsNotPresent("CP_CAP_LIMIT_MOUNTS")
Could we extract "CP_CAP_LIMIT_MOUNTS" to constant and replace this

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/RunPipelineTest.java
>  import static com.codeborne.selenide.Selectors.byClassName;
Clean up the unused import statements, please

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/SamplesMetadataTest.java
> +//        sleep(20, SECONDS);
Could this be cleaned?

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/SystemLoggingTest.java
> +                        .filterByField("User", admin.login)
Let's extract "User" to constant and replace its everywhere

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/LogAO.java
> +
Could be cleaned up?

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +                .findBy(text("Edit")).waitUntil(exist, DEFAULT_TIMEOUT).click();
Could this to be extracted to EDIT primitive?

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +                .findBy(text("Save")).waitUntil(exist, DEFAULT_TIMEOUT);
Could this to be extracted to SAVE primitive?

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +        $(className("ant-modal-content")).waitUntil(not(exist), DEFAULT_TIMEOUT);
Could this to be extracted to CONTENT primitive?

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +                .findBy(text("Save")).click();
The same as above

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +        editor.shouldBe();
Could this to be extracted to EDITOR primitive?

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +    public PipelineCodeTabAO waitUntilSaveEnding() {
Can be private

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineGraphTabAO.java
> +import static com.codeborne.selenide.Condition.exist;
Clean up the unused import statements, please

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineGraphTabAO.java
> +import static com.epam.pipeline.autotests.utils.C.DEFAULT_TIMEOUT;
Clean up the unused import statements, please

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineSelection.java
> +        context().$(className("ant-table-content")).waitUntil(exist, DEFAULT_TIMEOUT);
Could this to be extracted to TABLE primitive?

2024-04-17 09:12 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/SystemManagementAO.java
> +                    .getAttribute("value");
Could this be better to extract filters to primitives?

2024-05-08 13:26 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/LaunchLimitMountsTest.java
> +                .ensureParameterIsNotPresent("CP_CAP_LIMIT_MOUNTS")
Done

2024-05-08 13:27 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/RunPipelineTest.java
>  import static com.codeborne.selenide.Selectors.byClassName;
Done

2024-05-08 13:34 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/SystemLoggingTest.java
> +                        .filterByField("User", admin.login)
Done

2024-05-08 13:37 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/LogAO.java
> +
Done

2024-05-08 13:39 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/SamplesMetadataTest.java
> +//        sleep(20, SECONDS);
Done

2024-05-08 14:22 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +                .findBy(text("Edit")).waitUntil(exist, DEFAULT_TIMEOUT).click();
Done

2024-05-08 14:22 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +                .findBy(text("Save")).waitUntil(exist, DEFAULT_TIMEOUT);
Done

2024-05-08 14:30 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +                .findBy(text("Save")).click();
Done

2024-05-08 14:37 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineGraphTabAO.java
> +import static com.epam.pipeline.autotests.utils.C.DEFAULT_TIMEOUT;
Done

2024-05-08 14:38 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineGraphTabAO.java
> +import static com.codeborne.selenide.Condition.exist;
Done

2024-05-08 14:42 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +    public PipelineCodeTabAO waitUntilSaveEnding() {
Done

2024-05-08 14:52 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +        editor.shouldBe();
Done

2024-05-08 15:19 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineSelection.java
> +        context().$(className("ant-table-content")).waitUntil(exist, DEFAULT_TIMEOUT);
Done

2024-05-08 18:49 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/PipelineCodeTabAO.java
> +        $(className("ant-modal-content")).waitUntil(not(exist), DEFAULT_TIMEOUT);
Done

2024-05-21 07:35 UTC, kamyshova approved these changes

2024-05-21 08:01 UTC, merged