Gui improvements 28 06 2024
epam/cloud-pipeline pull request #3762
Opened 2024-11-06 11:57 UTC by maryvictol

This PR provides following updates:
-  Parameters form was updated according Support pretty names and icons in run parameters #3645
- Log message for Forcible terminate instances if the job is stuck in umont #2736 test was changed
- Error message for the run Pause confirmation popup  was changed
- Tests for luigi graph tab were disabled
- Multipaging for Cluster tab was added

2024-11-08 09:42 UTC, kamyshova requested changes

2024-11-08 09:42 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/RunPipelineTest.java
> +                .collect(toList()).isEmpty()) {
Could we simplify this to `clusterMenu().context().$$(node()).stream().anyMatch(not(master()))`?

2024-11-08 09:42 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/RunPipelineTest.java
> +    private void checkNodes() {
Maybe it will be better to use just one forEach() where we check the condition for each node() instead of the same two stream

2024-11-08 09:42 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/StorageRulesTabAO.java
> +        $$(className("ant-confirm-title")).filter(text("Do you want to delete rule")).first()
Could we add line breaks?

2024-11-08 09:42 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/ToolSettings.java
> +        return this;
Could we reuse parameter logic from RunParameterAO?

2024-11-08 09:42 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/mixins/Authorization.java
> +import static com.codeborne.selenide.Condition.exist;
Clean up?

2024-11-08 09:42 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/utils/C.java
> +        SSH_CLOUD_REGION = conf.getProperty("e2e.ssh.cloud.region");
I believe we should add this config to the `default.conf` too

2024-11-08 10:16 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/mixins/Authorization.java
> +import static com.codeborne.selenide.Condition.exist;
Done

2024-11-08 10:19 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/StorageRulesTabAO.java
> +        $$(className("ant-confirm-title")).filter(text("Do you want to delete rule")).first()
Done

2024-11-08 10:29 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/RunPipelineTest.java
> +                .collect(toList()).isEmpty()) {
Done

2024-11-08 13:24 UTC, maryvictol commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/RunPipelineTest.java
> +    private void checkNodes() {
Done

2024-12-24 09:14 UTC, kamyshova approved these changes

2024-12-24 09:14 UTC, kamyshova commented on e2e/gui/src/test/java/com/epam/pipeline/autotests/ao/ToolSettings.java
> +    public ToolParameterAO getParameterByIndex(int parameterIndex) {
This method is not used

2024-12-26 15:33 UTC, merged