Issue 623 Cloud Pipeline shall allow to "block" the user
epam/cloud-pipeline pull request #627
Opened 2019-08-27 16:49 UTC by Wedds

PR solves issue #623
It allows blocking a user to deny his access to the account. 

- `blocked` field is added to PipelineUser model and to user table in DB as well as flyway migration script
- Handling of `blocked` field is implemented in UserDao and related XML-file
- `updateUserBlockingStatus` method added to API in UserController
- Handling of `blocked` user status for authorization step is provided at SAMLUserDetailsServiceImpl class
- Necessary tests for new functionality of UserManager and SAMLUserDetailsServiceImpl classes were specified

2019-09-03 10:29 UTC, ekazachkova requested changes

2019-09-03 10:29 UTC, ekazachkova commented on api/src/main/java/com/epam/pipeline/controller/user/UserController.java
> +    @RequestMapping(value = "/user/{id}/block", method = RequestMethod.PUT)
Could we use `PutMapping` annotation here?

2019-09-03 10:29 UTC, ekazachkova commented on api/src/main/java/com/epam/pipeline/manager/user/UserManager.java
> +    public PipelineUser updateUserBlockingStatus(Long id, final boolean blockStatus) {
Please, make final method arguments and local fields

2019-09-03 10:29 UTC, ekazachkova commented on api/src/main/resources/db/migration/v2019.08.24_12.00__Issue623_add_user_blocking_support.sql
> +ALTER TABLE pipeline.user ADD blocked boolean DEFAULT false;
Please, don't forget to add empty line at the end of the file

2019-09-03 10:29 UTC, ekazachkova commented on api/src/test/java/com/epam/pipeline/manager/user/UserManagerTest.java
> +    private void compareAllFieldOfUsers(PipelineUser firstUser, PipelineUser secondUser) {
The method arguments names are a little bit unclear. I would prefer to rename args:
first -> expected
second -> actual
Also, could you make method arguments final.

2019-09-03 11:52 UTC, Wedds commented on api/src/main/java/com/epam/pipeline/controller/user/UserController.java
> +    @RequestMapping(value = "/user/{id}/block", method = RequestMethod.PUT)
Done

2019-09-03 11:53 UTC, Wedds commented on api/src/main/java/com/epam/pipeline/manager/user/UserManager.java
> +    public PipelineUser updateUserBlockingStatus(Long id, final boolean blockStatus) {
Done

2019-09-03 11:53 UTC, Wedds commented on api/src/main/resources/db/migration/v2019.08.24_12.00__Issue623_add_user_blocking_support.sql
> +ALTER TABLE pipeline.user ADD blocked boolean DEFAULT false;
Done

2019-09-03 11:53 UTC, Wedds commented on api/src/test/java/com/epam/pipeline/manager/user/UserManagerTest.java
> +    private void compareAllFieldOfUsers(PipelineUser firstUser, PipelineUser secondUser) {
Done

2019-09-03 16:48 UTC, ekazachkova approved these changes

2019-09-04 10:17 UTC, mzueva requested changes
Test `RoleDaoTest.testLoadRolesWithUsers()` fails, please check RoleDao queries.

2019-09-04 16:42 UTC, mzueva requested changes
The same changes are required for `loadRoleWithUsersQuery`

2019-09-05 10:27 UTC, mzueva approved these changes

2019-09-05 10:27 UTC, merged