(issue #624) Fix bug when IDLE tag wasn't set after a long time
epam/cloud-pipeline pull request #763
Opened 2019-10-22 10:06 UTC by SilinPavel

This PR related to #624 
It fixes bug when check nodes for CPU usage can be skipped when `system.max.idle.timeout.minutes` set to 1, it this case some of the data can be unalienable at the moment in elastic search. This PR move a window for monitoring request.

2019-10-23 12:21 UTC, tcibinan requested changes

2019-10-23 12:21 UTC, tcibinan commented on api/src/main/java/com/epam/pipeline/dao/monitoring/metricrequester/CPURequester.java
> +                .filter(b -> Double.isFinite(((Avg) b.getAggregations().get(AVG_AGGREGATION + USAGE_RATE)).getValue()))
Probably we could remove duplicated code by using temporary `Pair` object. Something like the following. Moreover we can reuse such code in all requesters.
```java
buckets
.map(b -> Pair.of(b.getKey().toString(), ((Avg) b.getAggregations().get(AVG_AGGREGATION + NODE_UTILIZATION)).getValue()))
.filter(utilizationEntry -> Double.isFinite(utilizationEntry.getRight()))
.collect(Collectors.toMap(Pair::getLeft, Pair::getRight));
```

2019-10-23 12:21 UTC, tcibinan commented on api/src/main/java/com/epam/pipeline/dao/monitoring/metricrequester/CPURequester.java
> +                .filter(b -> Double.isFinite(((Avg) b.getAggregations().get(AVG_AGGREGATION + USAGE_RATE)).getValue()))
Btw, there is a handy null-safe `AbstractMetricRequester.doubleValue` function which can be used to reduce boilerplate code. Moreother it already filters out infinite numbers.
```
doubleValue(aggregations(b), AVG_AGGREGATION + NODE_UTILIZATION))
```

2019-10-23 12:21 UTC, tcibinan commented on api/src/main/java/com/epam/pipeline/dao/monitoring/metricrequester/MemoryRequester.java
> +                .filter(b -> Double.isFinite(((Avg) b.getAggregations()
Same here.

2019-10-23 12:21 UTC, tcibinan commented on api/src/main/java/com/epam/pipeline/manager/cluster/performancemonitoring/ResourceMonitoringManager.java
> +                                previousMinute.minusMinutes(timeRange), previousMinute)));
Probably the right end of the monitoring period can be `now()`? In this case actual time range will be bigger then the one specified in the preference but at least we will receive relevant stats.

2019-10-23 13:39 UTC, tcibinan commented on api/src/main/java/com/epam/pipeline/dao/monitoring/metricrequester/AbstractMetricRequester.java
> +                        doubleValue(b.getAggregations().asList(), subAggName))
I would suggest to use `aggregations(b)` call here rather than `b.getAggregations().asList()`. It does just the same but is null-safe.

2019-10-23 13:42 UTC, tcibinan approved these changes

2019-10-28 09:19 UTC, mzueva approved these changes

2019-10-28 09:19 UTC, merged