The 'Browse filesystem' feature description added into Release Notes …
epam/cloud-pipeline pull request #810
Opened 2019-11-18 12:43 UTC by NewOlya

2019-11-21 14:42 UTC, NShaforostov requested changes
I've left some comments, view them and make corresponding edits, please.

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/11_Manage_Runs/11._Manage_Runs.md
> +| **BROWSE** | Allows to open a Storage browser so user can view, download, upload and delete files and directories for the current active run precisely. |
I suggest to put minor correctives:

```suggestion
| **BROWSE** | Allows to open the run instance filesystem in a Storage browser Web GUI - so the user can view, download, upload, delete files and directories for the current active run. |
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +To browse node filesystem go to the runs page:
```suggestion
To browse node filesystem go to the **Run logs** page.
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +    ![CP_v.0.16_ReleaseNotes](attachments/NodeFilesystem_01.png)
Suggest not to show any pictures at this place
```suggestion
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +After a job had been initialized the `Browse` hyperlink become available to the users via the Cloud Pipeline Web GUI within a run's log form and a dashboard tiles of the running pipelines:
```suggestion
After a job had been initialized the `Browse` hyperlink become available to the users:
```
Or what did you mean about "dashboard tiles"?

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +Click on the hyperlink to view node's filesystem:
```suggestion
Click the hyperlink to view the node's filesystem:  
```
Don't forget to put 2 spaces at the end of a line if you want to add the line break (without an empty line) in `Markdown` documents

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +The local File Manager window will be opened. Select files that you want to upload and press the Open button:
```suggestion
The local File Manager window will be opened. Select files that you want to upload and press the Open button:  
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +The Cloud Pipeline will display `Operations` list with all selected files and uploading statuses:
```suggestion
The Cloud Pipeline will display `Operations` list with all selected files and uploading statuses:  
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +After the uploading will be completed the system will update files statuses:
```suggestion
After the upload is completed the system will update the file statuses:  
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +To collapse the Operations window press cross button.
```suggestion
To collapse the Operations window press cross button.  
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +
Add small info+picture(s) about folder navigation in the FS Browser

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +## Download files through node's file browser
```suggestion
## Download files/directories through node's file browser
```
And correct, please, the corresponding item of the page content

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +    ![CP_v.0.16_ReleaseNotes](attachments/NodeFilesystem_10.png)
```suggestion
    ![CP_v.0.16_ReleaseNotes](attachments/NodeFilesystem_11.png)
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +    ![CP_v.0.16_ReleaseNotes](attachments/NodeFilesystem_11.png)
```suggestion
    ![CP_v.0.16_ReleaseNotes](attachments/NodeFilesystem_10.png)
```
Maybe this replacement is better?

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +
Add, please, a picture with a downloaded gzipped directory. Because now, it's hard to realize why you click to download the 'cloud-data' directory but on the next picture there is only one downloaded file (not *.gzip)

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +## Delete files through node's file browser
```suggestion
## Delete files/directories through node's file browser
```
And correct, please, the corresponding item of the page content

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +To delete file or directory user needs to press the `Delete` button:
```suggestion
To delete file or directory user needs to press the `Delete` button:  
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +    ![CP_v.0.16_ReleaseNotes](attachments/NodeFilesystem_12.png)
```suggestion
    ![CP_v.0.16_ReleaseNotes](attachments/NodeFilesystem_12.png)  
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +The confirmation window will be displayed. Press OK to delete file or directory:
```suggestion
The confirmation window will be displayed. Press the OK button to delete:
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +    ![CP_v.0.16_ReleaseNotes](attachments/NodeFilesystem_13.png)'
```suggestion
    ![CP_v.0.16_ReleaseNotes](attachments/NodeFilesystem_13.png)
```
Please, remove from the picture the part with the text in Russian

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +## Search files at node's file browser
```suggestion
## Search files/directories at node's file browser
```
And correct, please, the corresponding item of the page content

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +To search inside current directory through files and directories click on the address panel and type desired file or directory name:
```suggestion
To search inside the current directory through files and directories - click the address panel and type desired file or directory name:  
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +    ![CP_v.0.16_ReleaseNotes](attachments/NodeFilesystem_14.png)
```suggestion
    ![CP_v.0.16_ReleaseNotes](attachments/NodeFilesystem_14.png)  
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/release_notes/v.0.16/v.0.16_-_Release_notes.md
> +- [Allowing to expose compute node FS to upload and download files](#allowing-to-expose-compute-node-FS-to-upload-and-download-files)
For correct work of anchor-links in `Markdown` documents - link addresses should be written in the lowercase
```suggestion
- [Allowing to expose compute node FS to upload and download files](#allowing-to-expose-compute-node-fs-to-upload-and-download-files)
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/release_notes/v.0.16/v.0.16_-_Release_notes.md
> +In the current version, direct exposure of the run's filesystem is supported. The "Browse" hyperlink is displayed in the **Active Run** dashboard after a job had been initialized:
```suggestion
In the current version, direct exposure of the run's filesystem is supported. The **BROWSE** hyperlink is displayed on the **Run logs** page after a job had been initialized:  
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/release_notes/v.0.16/v.0.16_-_Release_notes.md
> +User can click the link and a Storage browser Web GUI will be loaded:
```suggestion
User can click the link and a Storage browser Web GUI will be loaded:  
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/release_notes/v.0.16/v.0.16_-_Release_notes.md
> +- view files and directories
Add an empty line before the list
```suggestion

- view files and directories
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/release_notes/v.0.16/v.0.16_-_Release_notes.md
> +- download and delete files and directories
```suggestion
- download and delete files and directories  
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/release_notes/v.0.16/v.0.16_-_Release_notes.md
> +- upload files and directories
```suggestion
- upload files and directories  
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/release_notes/v.0.16/v.0.16_-_Release_notes.md
> +- search files and directories
```suggestion
- search files and directories  
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/release_notes/v.0.16/v.0.16_-_Release_notes.md
> +For more details see [here](../..\manual\15_Interactive_services\15.4._Expose_node_filesystem.md).
```suggestion
For more details see [here](../../manual/15_Interactive_services/15.4._Expose_node_filesystem.md).
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/mkdocs.yml
> +
Extra empty line
```suggestion
```

2019-11-21 14:42 UTC, NShaforostov commented on docs/md/release_notes/v.0.16/v.0.16_-_Release_notes.md
> +
Extra empty line
```suggestion
```

2019-11-21 18:08 UTC, NShaforostov requested changes

2019-11-21 18:08 UTC, NShaforostov commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +- [Upload files through node's file browser](#Upload-files-through-node's-file-browser)
For correct work of anchor-links in `Markdown` documents - link addresses should be written in the lowercase, spaces should be replaced by '-' symbol, other auxiliary symbols are also replaced by '-' or removed
```suggestion
- [Upload files through node's file browser](#upload-files-through-nodes-file-browser)
```
Analogically correct, please, other content items.

2019-11-22 12:15 UTC, NewOlya commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +## Download files through node's file browser
Done

2019-11-22 13:35 UTC, NewOlya commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +
Done

2019-11-22 13:48 UTC, NewOlya commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +
Done

2019-11-22 14:02 UTC, NewOlya commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +    ![CP_v.0.16_ReleaseNotes](attachments/NodeFilesystem_10.png)
Done

2019-11-22 14:02 UTC, NewOlya commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +    ![CP_v.0.16_ReleaseNotes](attachments/NodeFilesystem_11.png)
Done

2019-11-22 14:04 UTC, NewOlya commented on docs/md/manual/15_Interactive_services/15.4._Expose_node_filesystem.md
> +## Search files at node's file browser
Done

2019-11-22 17:17 UTC, NShaforostov approved these changes

2019-12-16 17:58 UTC, merged