pipe storage du for S3 and NFS
epam/cloud-pipeline pull request #979
Opened 2020-02-21 13:14 UTC by ekazachkova

This PR provides implementation for issue #548 

The following changes were added:
- a new API method `GET datastorage/path/usage` that calculates datastorage usage statistics. The data is taken from elasticsearch.
- method for loading NFS datastorages by name or ID was fixed.
- a new CLI option `pipe storage du` was added. If `path` is not specified all buckets will be listed with `GET datastorage/path/usage` API method call. If path was specified and it's not NFS the bucket will be listed with cloud provider directly. If path has NFS type the data will be loaded with `GET datastorage/path/usage` API method call

2020-02-21 15:10 UTC, mzueva requested changes

2020-02-21 15:10 UTC, mzueva commented on pipe-cli/pipe.py
> +def storage_copy_item(path, format, depth):
It seems that method name is misleading

2020-02-21 15:10 UTC, mzueva commented on pipe-cli/src/utilities/storage/s3.py
> +                        if relative_path:
Could we extract this logic into a separate method to make it more readable?

2020-02-21 15:10 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/security/GrantPermissionManager.java
> +        AbstractSecuredEntity storage = entityManager.loadByNameOrId(AclClass.DATA_STORAGE, identifier);
missing `final`

2020-02-26 19:32 UTC, mzueva commented
@ekazachkova Could you please add nfs storage path format to the PR description?

2020-02-26 19:37 UTC, mzueva requested changes

2020-02-26 19:37 UTC, mzueva commented on api/src/main/java/com/epam/pipeline/manager/security/GrantPermissionManager.java
> +        AbstractSecuredEntity storage = entityManager.loadByNameOrId(AclClass.DATA_STORAGE, identifier);
still missing `final`

2020-02-27 11:49 UTC, ekazachkova commented
Several remarks for this implementation:
1. It would be better to specify storage path with single option, e.g. `pipe storage du s3://storage_1/folder1`. But in this case it's not clear how to parse NFS storage path since it is difficult to determine where the storage name and were relative path. 
The idea is to implement NFS path parsing into the server part:
- determine deepest folder path from specified path
- try to load storage by this name
- if the storage does not exists - level up folder path and try to load storage by new name
- repeat until the storage is found
2. `--depth` option is not supported for NFS storages. One of the possible ways to solve this problem is to use elasticsearch. The idea is to store depth information for paths.

2020-02-28 11:04 UTC, merged